### ISSUE TITLE
Drilldown in case of KPIs based on queries

### ISSUE THREAD

**Issue by Mraimou** [OCA/mis-builder#179]
Hello,
I can't use drildown option in case of kpis based on queries.
I guess that this restriction is caused by the function eval_expressions in mis.report.
do you have any suggestions to expand this option without causing conflict with mis_builder logique?
Thank you.

**Comment by sbidoul** [comment]
Drilldown is currently implemented only for accounting expression.

For queries, the main issue is it's not easy to know that a given expression has parts coming from queries, and which queries. Also what to do if an expression use that from queries on different models?

**Comment by rvalyi** [comment]
just hit that one. I tried to consolidate analytic lines or financial provisions using a query but the no drill down issue is kind of blocker.

Alternatively, I was defining an SQL view (like in the committed purchase demo) with a UNION ALL of the various models. But when you do this, you loose informations for the many2many relations, that is the analytic_tag_ids which really sucks too. Yet managing complex projects such as Odoo implementation using analytic_tags was applealing...

Not sure which way is the best at the end. A third way might be to go the SQL view way and denormalize the m2m tags as a string of comma separarted tags. That would mismatch the global analytic_tags_id filter but you could still use them in your KPI...
Thinking loud...

**Comment by rvalyi** [comment]
well, one can actually define virtual many2many relation tables for composite SQL view fact tables. It's not trivial tough because composite (UNION ALL) SQL view tables tend to have duplicate ids. I worked around that by offsetting ids from different tables by some millions...

All in all mis-builder would be quite more powerfull with a query drill down. I don't think the concept is hard: a mis report instance has only a small number of named queries. By searching these named queries in a KPI expression, one can easily know the involved queries. Then it would be about having a popup (or some kind of multi-link roll over) that would offer the choice to drill down on the records of the object of the named query you want.

A malicious user could still screw it by defining a named query with a name containing the name of another named query. But in that case a simple check to avoid such sabotage could be used.

Finally most of the time, a KPI would involve only one query and may be it's not that hard to get that simple case working.

**Comment by legalsylvain** [comment]
>  It's not trivial tough because composite (UNION ALL) SQL view tables tend to have duplicate ids. I worked around that by offsetting ids from different tables by some millions...

I maybe not understand correctly your problem, but regarding the UNION ALL, you can easely create an intermediate SQL materialized views with ``bi_sql_editor``. It handles correctly and automatically ids. (no need to offset...)
One of my view has this sql request : (unioning intermediate materialized views ...)

```
SELECT
    x_company_id,
    x_product_id,
    x_user_id,
    ...
FROM   ( select * from x_bi_sql_view___account_invoice_line
UNION ALL  select * from x_bi_sql_view___pos_order_line) as temp
GROUP BY
    x_company_id,
    x_product_id,
    ...
```

Maybe you can then use this new model in mis-builder...
just an idea, maybe it's not relevant.
