### ISSUE TITLE
Add date/time of report generation in XLS export

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#191]
This could be added at the bottom of the report.

**Comment by apineux** [comment]
@sbidoul In my opinion, adding the date/time at the end of the report (in a cell) can be bad for end users. If you add that information in a new cell at the end, this can be interpreted as a data of the report instead of a "meta data". What do you think? Can you be more precise in the way you want to display that date/time.

**Comment by sbidoul** [comment]
The idea is to have a kind of footer saying "Report generated at YYYY-MM-DD HH:MM:SS", perhaps in small italics or something like that. 

This is a frequently requested feature to give a more professional look to the output. For PDF exports, this is not an issue because the date/time is usually part of the internal report template.

**Comment by sbidoul** [comment]
![image](https://user-images.githubusercontent.com/692075/57518945-8e953d80-731a-11e9-87b1-95f658ebd93a.png)
