### ISSUE TITLE
Restore _intersect_days model method

### ISSUE THREAD

**Issue by svalaeys** [OCA/mis-builder#280]
Hi Stephane, 
Thank you very much for all the latest changes in mis_builder and mis_builder_budget. Budgets by accounts, filters on analytics, everything I ever wanted. Thanks.
My question has to do with the method intersect_days in mis_kpi_data.py.

This method used to be the class method _intersect_days of MisKpiData. I had overwritten this method to achieve a different calculation of the pro-rata part of the budget item for a column. The reason is that there is no doubt that a great selling point of MIS Builder Budget is the automated pro-rated calculation of budget items. But for all my clients, they want a budget split equally in twelve months. This makes a lot of sense for rents, payroll, etc. 

Correct me if I am wrong, but I think the only way to achieve this in base is to create 12 different budget items each worth a month. But by doing so it takes away the clean, one-budget-item-per-year advantage of MIS Budget.

The override of _intersect_days took care of that for me. It was full of assumptions (30-day months) and inflexibility (a report column must fully enclose a period to take it into account) but it did its job for the most common cases I am encountering.

Now that it's not a class method anymore, it's a little less clean to override it. Therefore I have two questions:
- How do think about non pure day-based pro rata temporis needs? Do you systematically create multiple lines in those cases?
- Would you consider putting intersect_days back as a class method to ease its override?

Thanks for your thoughts.   

Stephane

**Comment by sbidoul** [comment]
> Correct me if I am wrong, but I think the only way to achieve this in base is to create 12 different budget items each worth a month. But by doing so it takes away the clean, one-budget-item-per-year advantage of MIS Budget.

That is correct. 

> But for all my clients, they want a budget split equally in twelve months. This makes a lot of sense for rents, payroll, etc.

Yes that is a request I hear sometimes.

I've not given deep thought to it, but it would probably be a good feature if we find a functional design that is generic enough and reasonably simple to configure. Feel free to open an issue if you have ideas about such a design.

> Would you consider putting intersect_days back as a class method to ease its override?

I factored it out because I needed it for budget by accounts too, but yes I can add it back. I'll rename this issue to track this.

Thank you for the feedback!

**Comment by svalaeys** [comment]
In a way I wonder sometimes if this bit should not be sealed off in some other module. I mean, after all, we are not trying to do something that is strictly related to budgeting. We are trying to compute the ratio period days over total days in different ways. Maybe date_range, even though we are dealing with dates only as opposed to ranges?

In terms of design, clearly we have to be careful not to overwhelm the user. But we can learn from what you've already done with styles to do that. To me, this day calculation should be on the budget item itself. To avoid having to specify it on every single line, we could simply have a default period calculation field at the budget level (akin to the styles level on the MIS report definition) and the possibility to be more specific item by item (akin to styles on kpis).

I know I am already needlessly optimising here, but I just want to throw out there that I think a computation structure where all date ratios would be computed before financial calculations start would allow to compute this data once per start date-end date-range as opposed to for every single item.

**Comment by sbidoul** [comment]
@svalaeys thank you for the input. So far it's still fuzzy in my head, and I'm under the impression it's hard to provide a UI that cover enough use cases, knowing that people who really want to fine tune can add detail lines in their budgets with the granularity they desire.

So let's close this issue since what it's title say is resolved and feel free to open another one if you wish to further explore the feature.
