### ISSUE TITLE
default status of temporary is False and method write also False.

### ISSUE THREAD

**Issue by farazbdm** [OCA/mis-builder#301]
https://github.com/OCA/mis-builder/blob/b9bda3c7f57dba51bb0fa64974b7df04776cd8da/mis_builder/models/mis_report_instance.py#L599

**Comment by farazbdm** [comment]
i believe it should be:
self.write({"temporary": True})

and then in the Form view the invisible attribute must be removed for save button, or inversed.

**Comment by farazbdm** [comment]
@pedrobaeza i am new to github, apologies if standard practice not followed for reporting issue

**Comment by pedrobaeza** [comment]
Well, an issue is something that works incorrectly, not something that you suspect is incorrect. So what are the steps to reproduce a problem with existing code?

**Comment by farazbdm** [comment]
Thanks for your prompt response
To recreate:
There are 2 menus under Reports > MIS Reports

Mis Report
Last Generated Report

Difference between both is with ‘temporary’ boolean
Which is toggled by method of button SAVE
That should write temporary from False to True

Where as this button not appears at all,
Method not write temporary value from False to True
This makes Last Generated Reports Menu always empty no matter what.

**Comment by sbidoul** [comment]
@farazda1 thanks for your question.

This behaviour is by design, and the `temporary` flag is meant for reports generated on the fly from wizards like this:

https://github.com/OCA/mis-builder/blob/b9bda3c7f57dba51bb0fa64974b7df04776cd8da/mis_builder/models/mis_report.py#L522

You can see an example here for a vat declaration:

https://github.com/OCA/l10n-belgium/blob/50ab91a8f7b5322ccfd824d9029fece4910cc653/l10n_be_mis_reports/data/mis_report_vat.xml#L7-L14

**Comment by farazbdm** [comment]
@pedrobaeza @sbidoul thanks alot, OCA rocks
