### ISSUE TITLE
[12.0] mis_builder: Incorrect amount in account details when mixing account expressions with other KPIs

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/mis-builder#306]
- Define a new MIS template with these KPI lines:
  * Line 1 - `name1` - bale[430%] + name2
  * Line 2 - `name2` - bale[431%]
- Put 1000 on balance of 430000 account.
- Put 500 on balance of 431000 account.
- Don't disable account expansion.
- Preview a MIS report with that template and the date range where the balances has been put.

Result: You get 1500 in the 430000 account, summing its balance with the amount of `name2` instead of 1000. It happens to any possible account directly included in the Line 1 expression as well.

Tested on 12, but probably happening in the rest of the versions.

**Comment by pedrobaeza** [comment]
@sbidoul can you take a look to this?

**Comment by sbidoul** [comment]
This is how it works: when computing detail by account, it basically evaluates the same expression, but replacing the bal/crd/deb expressions by the value of a single account at a time. The rest of the expression remains unchanged (`+ name2` in this case).

The easiest is probably to refactor the report to have a line with `name0 = -bale[430%]` and then `name1 = name0 + name2`.

**Comment by pedrobaeza** [comment]
I can't change the formulas, as they are determined by the authority, and they should be that way, but for me makes no sense than the account expansion detail includes other amounts that are not directly related to that account. And not only that, if the line 1 contains several accounts, each account will be sum with the amount of the line 2, so the sum of all of these accounts won't be the total amount of the line. Can this be avoided somehow without changing the expression itself? I think this can be considered a bug.

**Comment by sbidoul** [comment]
It's not an easy change. For instance if your formula is `-bale[431%] + name2` how should we determine that we need to ignore `+name2` but keep the minus in front of bale?

The workaround I suggest is not changing the formula, it's adding a line in the report.

**Comment by pedrobaeza** [comment]
Well, I think each fragment can be identified: sign (or nothing) + sub-expression.

As said, I can't add a line, as the format if fixed by the authority, or am I missing something?

**Comment by pasgou** [comment]
Could I ?
@pedrobaeza what do you mean when you say "fixed by the authority"?

**Comment by pedrobaeza** [comment]
In Spain, it's the government/authority who establishes the lines to present in the report.

**Comment by pasgou** [comment]
Ok, as in France.
But if I understand well after reading [this](http://www.icac.meh.es/Documentos/Contabilidad/1.Nacional/01.PGC/01.Texto%20en%20vigor%20a%20partir%201-01-2016/4.PGC%202016-%20Modificaciones%20RD602-2016.pdf) page#110 and [this](http://www.icac.meh.es/Documentos/CONTABILIDAD/PGC%20Ingles.pdf) page#112 (as I don't know Spanish) and because of my role in France (Chartered Accountant) could I purpose the same thing as @sbidoul 

The reports have sub.totals. Here we have 
III.  Deudores comerciales y otras cuentas a cobrar. = 1. Clientes por ventas y prestaciones de servicios + 2. Clientes, empresas del grupo y asociadas. + 3.      Deudores      varios.     + 4.      Personal.  +    5. Activos por impuesto corriente.+ 6. Otros créditos con las Administraciones Públicas. +7. Accionistas (socios) por desembolsos exigidos
and (for example)
1. Clientes por ventas y prestaciones de servicios = bale[430%]+bale[431%]+ .... -bale[437%] - ....
2. Clientes, empresas del grupo y asociadas. = bale[433%] + .....
where 1. and 2. are independent.

There is perhaps a bug, but in your case, it seems that the workaround exists and is conform to your accountancies rules.

Hope to have helped.

**Comment by pedrobaeza** [comment]
@pasgou thanks for checking this. Indeed, seeing you reference, the report don't have the problem:

![Selección_024](https://user-images.githubusercontent.com/7165771/94340140-9df45400-ffff-11ea-847c-60c5a046e7c5.png)

as there's no unfolding of that section, on contrary of what we have in the MIS template:

![Selección_025](https://user-images.githubusercontent.com/7165771/94340163-da27b480-ffff-11ea-8f8a-ad23d86dbb5f.png)

Your reference is from 2016, but the CoA is from 2008, so maybe there has been an update. I will check official documentation to see and tell you back.
