### ISSUE TITLE
mis_builder_budget not migrated

### ISSUE THREAD

**Issue by C2dricLeroy** [OCA/mis-builder#612]
Hello all,

I'll be concise, the module "mis_builder_budget' is not migrated in version 17.0, but is still in version 16.0.

**Comment by C2dricLeroy** [comment]
Same for mis_builder

**Comment by vdewulf** [comment]
Hello,
There is a PR for the migration of mis_builder to v17:
https://github.com/OCA/mis-builder/pull/607
When looking for a module in a newer version, you can always check on the "Pull Requests" tab to see if something is cooking by our kind contributors.
In addition, you can see the list of all modules to be migrated in a repository in a dedicated issue, like this one: 
https://github.com/OCA/mis-builder/issues/582
So no work in progress for mis_builder_budget.
Do you use those modules for your own database or for your customers if you're an Odoo integrator?
To help speed the process, you could:
* if you have technical skills or someone in your team: start the migration yourself and propose a PR, and/or review the current PR's
* if you don't have technical skills but know how the module works, you could test the proposed module in the runboat, from the PR of migration.
* in addition to this list, you might in the near future want to become an official OCA subscriber (new programto be launched in September) and contribute with money to the building and strenthening of the association: we hope to receive funding to structure and help our contributors in order to get the most popular and mature OCA modules ready in the newest versions as soon as possible (this part of the program will probably be launched in 2025).

Hope this message helps you understand the context and ways to contribute on your side as well! If you have any question, don't hesitate to ask and ping me.

Have a good day,
Virginie
