### ISSUE TITLE
Backport widget code improvements from 11 to 10 and 9

### ISSUE THREAD

**Issue by sbidoul** [OCA/mis-builder#75]
The widget implementation is better in v11
* the code is cleaner
* in theory it allows the inclusion of a mis report widget in a form view

This issue is to test if the v11 code works in v10 and v9 (from reading the widget API documentation, it should).

**Comment by sbidoul** [comment]
@benwillig if you want to have a look.

**Comment by benwillig** [comment]
About the v11 code, I'm wondering if there was a specific reason to directly create a FieldWidget instead of having a Widget which takes the report ID as parameter. Then the FieldWidget would simply instanciate the base Widget.

There is also the ```_rpc``` calls which could be converted to Model(<model>).call, but it won't change anything.
